pipeline{
    agent { label 'docker'}

    stages{
        stage('Build Image'){
            steps{
                script{
                sh 'docker build -t mongodatabase:1.1 mogoDB/'
            }
        }
            
         }

        stage('Push Image to Docker hub'){
            steps{
                script{

                    withCredentials([usernamePassword(credentialsId: 'Docker-hub-cred', passwordVariable: 'password', usernameVariable: 'username')]) {
    
                     sh '''
                    docker login --username $username --password $password
                    docker image tag mongodatabase:1.1 sudheer5561/mongodbsamplerepo:1.1
                    docker push sudheer5561/mongodbsamplerepo:1.1

                    '''
                    }                   


                }
            }
        }
    }
}
